project:
  type: website
  pre-render: 
    - "rm -rf _site/*"
  post-render:
    - "python scripts/post-render.py"
  resources:
    - CNAME
  preview:
    port: 7777

website:
  title: "Seanczak"
  site-url:  https://randomrealizations.com/
  description: "A blog about data science, statistics, machine learning, and the scientific method"
  favicon: "favicon-wbg.png"
  margin-header: includes/subscribe.html
  # comments:
  #   utterances:
  #     repo: mcb00/blog
  #     issue-term: title
  image: opengraph.png
  open-graph:
    image: opengraph.png
    image-alt: "circle painted by hand in a single brush stroke"
    image-width: 1200
    image-height: 630
    title: "Seanczak blog"
    description: "this is sean's stats blog"
  navbar:
    background: dark
    # logo: logo.png
    right:
      - text: About
        href: about.qmd
      - text: Resources
        menu:
          - text: Python-Bloggers
            href: https://python-bloggers.com/
          
    tools:
      - icon: linkedin
        text: Sean on LinkedIn
        href: https://www.linkedin.com/in/sean-fronczak/
      - icon: github
        text: Sean on Github
        href: https://github.com/seanczak
format:
  html:
    theme: yeti # zephyr
      # light: flatly
      # dark: darkly
    css: styles.css
    include-in-header:
      - includes/umami.html



